### ISSUE TITLE
Rename Repository

### ISSUE THREAD

**Issue by scott-huberty** [lina-usc/eog-learn#16]
As discussed, It may be preferable to rename this package since it is associated with a specific manuscript and is not a general purpose tool for outside researchers to use. 

@christian-oreilly if you want, feel welcome to take unilateral action on renaming the repo to what you believe fits best.

**Comment by christian-oreilly** [comment]
Sorry for now following up on this yet. I did not think of renaming the repository per se. This repo has a branch slurm which also has a directory named slurm. That was intended to contain the code for running the analysis through slurm, but has I was having issues with the cluster, I just used plain multiprocessing and my laptop. This code was further expanded to include all the analyses we used for the paper. So, I was proposing renaming this directory from "slurm" to something like "paper_2024", removing the unused slurm stuff, and then merging this branch to the master. Would that work for you?

**Comment by scott-huberty** [comment]
Fine with me!
